name: "Check - Typecript"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "typescript/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          # cache: yarn

      - name: Install deps
        run: yarn install

      - name: Run tests
        run: npm run test
