name: "Build - Typecript DAYC"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "typescript/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: typescript/yarn.lock

      - name: Install deps
        run: yarn --cwd ./typescript install

      - name: Run build
        run: yarn --cwd ./typescript build:dayc
